name: dravessentials
main: wtf.drav.dravessentials.Main
version: 1.1
author: Drav
load: POSTWORLD
api-version: 1.16
depend: [LuckPerms]
commands:
   anick:
      description: Admin Nick
      usage: /anick
      permission: dravfix.anick
      permission-message: You don't have permission dravfix.anick!
      aliases: [adminnick]
   lasttimer:
      description: Gets the last specified scan
      usage: /lasttimer
      permission: dravfix.lasttimer
      permission-message: You don't have permission dravfix.lasttimer!
   scanmining:
      description: Scan Mining
      usage: /scanmining
      permission: dravfix.scanmining
      permission-message: You don't have permission dravfix.scanmining!
   showdiamonds:
      description: Shows Diamonds
      usage: /showdiamonds
      permission: dravfix.showdiamonds
      permission-message: You don't have permission dravfix.showdiamonds!
   balancereset:
      description: Balance Reset
      usage: /BalanceReset
      permission: dravfix.balancereset
      permission-message: You don't have permission dravfix.balancereset!
   topdragonhits:
      description: Top dragon hits
      usage: /topdragonhits
      permission: dravfix.topdragonhits
      permission-message: You don't have permission dravfix.topdragonhits!
   pkopengui:
      description: Opens Parkour GUI
      usage: /pkopengui